### ISSUE TITLE
SVG animation

### ISSUE THREAD

**Issue by Katarzina** [monterail/vueconf#27]
make install your project for explore how work svg animation but have no nothing - my hero-banner block is empty... can give some advice for setting Hero and LogoType components...

**Comment by shentao** [comment]
Hey! You could check out the slides and JSfiddle example of the animation.
http://slides.com/damiandulisz/vue-animations

**Comment by Katarzina** [comment]
Thank you..problem was :
`async mounted () {
!!!-->    if (process.BROWSER_BUILD) {`
